# .github/workflows/deploy-to-admin_beta.yml

on:
  push:
    branches:
      - master
name: 🚀 Deploy on valetudo.aaden.online

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Build Project
        run: |
          npm install
          npm run build
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: aaden.online
          server-dir: ./valetudo/
          #          username: ${{ secrets.ftp_username }}
          #          password: ${{ secrets.ftp_password }}
          username: u172534159.cong
          password: Innerken322.
          local-dir: ./dist/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
